## Daily AI Excercise - Numpy, Pytorch, Tensorflow - Transpose and Summation

In [1]:
import numpy as np

arr_1 = np.array([[1, 2], [3, 4]])

arr_transposed_1 = np.transpose(arr_1)

arr_transposed_2 = arr_1.T

print("array 1: \n", arr_1)
print("array 1 transposed, method 1: \n", arr_transposed_1)
print("array 1 transposed, method 2: \n", arr_transposed_2)

array 1: 
 [[1 2]
 [3 4]]
array 1 transposed, method 1: 
 [[1 3]
 [2 4]]
array 1 transposed, method 2: 
 [[1 3]
 [2 4]]


In [2]:
import torch

tensor_1 = torch.tensor([[1, 2], [3, 4]])

tensor_transposed_1 = tensor_1.t()

tensor_transposed_2 = torch.transpose(tensor_1, 0, 1)

print("tensor 1: \n", tensor_1)
print("tensor 1 transposed, method 1: \n", tensor_transposed_1)
print("tensor 1 transposed, method 2: \n", tensor_transposed_2)

tensor 1: 
 tensor([[1, 2],
        [3, 4]])
tensor 1 transposed, method 1: 
 tensor([[1, 3],
        [2, 4]])
tensor 1 transposed, method 2: 
 tensor([[1, 3],
        [2, 4]])


In [3]:
import tensorflow as tf

tensor_2 = tf.constant([[1, 2], [3, 4]])

tensor_transposed = tf.transpose(tensor_2)

print("tensor 1: \n", tensor_2)
print("tensor 1 transposed: \n", tensor_transposed)

tensor 1: 
 tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tensor 1 transposed: 
 tf.Tensor(
[[1 3]
 [2 4]], shape=(2, 2), dtype=int32)


### Summation

In [4]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

total_sum = np.sum(arr)

column_sum = np.sum(arr, axis=0)

row_sum = np.sum(arr, axis=1)

print("array: \n", arr)
print("total sum: ", total_sum)
print("column sum: ", column_sum)
print("row sum: ", row_sum)

array: 
 [[1 2 3]
 [4 5 6]]
total sum:  21
column sum:  [5 7 9]
row sum:  [ 6 15]


In [6]:
import torch

tensor_1 = torch.tensor([[1, 2, 3], [4, 5, 6]])

total_sum = torch.sum(tensor_1)

column_sum = torch.sum(tensor_1, dim=0)

row_sum = torch.sum(tensor_1, dim=1)

print("tensor 1: \n", tensor_1)
print("total sum: ", total_sum)
print("column sum: ", column_sum)
print("row sum: ", row_sum)

tensor 1: 
 tensor([[1, 2, 3],
        [4, 5, 6]])
total sum:  tensor(21)
column sum:  tensor([5, 7, 9])
row sum:  tensor([ 6, 15])


In [7]:
import tensorflow as tf

tensor_2 = tf.constant([[1, 2, 3], [4, 5, 6]])

total_sum = tf.reduce_sum(tensor_2)

column_sum = tf.reduce_sum(tensor_2, axis=0)

row_sum = tf.reduce_sum(tensor_2, axis=1)

print("tensor 2: \n", tensor_2)
print("total sum: ", total_sum)
print("column sum: ", column_sum)
print("row sum: ", row_sum)

tensor 2: 
 tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
total sum:  tf.Tensor(21, shape=(), dtype=int32)
column sum:  tf.Tensor([5 7 9], shape=(3,), dtype=int32)
row sum:  tf.Tensor([ 6 15], shape=(2,), dtype=int32)


### Excercise

In [9]:
# write a program to create numpy array with random interger between [-10, 10] with shape (3, 4)
# then transpose the array

import numpy as np

arr = np.random.randint(-10, 10, (3, 4))

arr_transposed = np.transpose(arr)

print("array: \n", arr)
print("array transposed: \n", arr_transposed)

array: 
 [[ -8   4   8  -1]
 [  5   8 -10  -8]
 [  2   7  -6   8]]
array transposed: 
 [[ -8   5   2]
 [  4   8   7]
 [  8 -10  -6]
 [ -1  -8   8]]


In [ ]:
# write a program to create a Pytorch tensor with random interger between [-10, 10] with shape (3, 4)
# then do the matrix multiplication