## Daily AI Excercise - Numpy - Pytorch/ Tensorflow

In [1]:
import numpy as np
import torch
import tensorflow as tf

In [2]:
arr_zeros = np.zeros((3, 4))
print(f"NumPy array of zeros:\n{arr_zeros}")

tensor_zeros = torch.zeros((3, 4))
print(f"PyTorch tensor of zeros:\n{tensor_zeros}")

tensor_zeros = tf.zeros((3, 4))
print(f"TensorFlow tensor of zeros:\n{tensor_zeros}")

NumPy array of zeros:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
PyTorch tensor of zeros:
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
TensorFlow tensor of zeros:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [3]:
arr_ones = np.ones((3, 4))
print(f"NumPy array of ones:\n{arr_ones}")

tensor_ones = torch.ones((3, 4))
print(f"PyTorch tensor of ones:\n{tensor_ones}")

tensor_ones = tf.ones((3, 4))
print(f"TensorFlow tensor of ones:\n{tensor_ones}")


NumPy array of ones:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
PyTorch tensor of ones:
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
TensorFlow tensor of ones:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [4]:
arr_full = np.full((3, 4), 5)
print(f"NumPy array of fives:\n{arr_full}")

tensor_full = torch.full((3, 4), 5)
print(f"PyTorch tensor of fives:\n{tensor_full}")

tensor_full = tf.fill((3, 4), 5)
print(f"TensorFlow tensor of fives:\n{tensor_full}")

NumPy array of fives:
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
PyTorch tensor of fives:
tensor([[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]])
TensorFlow tensor of fives:
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
