## Daily AI Excercise - Numpy Array and Pytorch

In [2]:
import numpy as np
import torch
import tensorflow as tf

In [3]:
print("PyTorch version: ", torch.__version__)
print("TensorFlow version: ", tf.__version__)

PyTorch version:  2.0.1+cpu
TensorFlow version:  2.12.0


In [5]:
list_1D = [1, 2, 3, 4, 5, 6, 7, 8, 9]

arr_1D = np.array(list_1D)
print("Numpy 1D array: ", arr_1D, type(arr_1D))

tensor_1D_pt = torch.tensor(list_1D)
print("PyTorch 1D tensor: ", tensor_1D_pt, type(tensor_1D_pt))

tensor_1D_tf = tf.convert_to_tensor(list_1D)
print("TensorFlow 1D tensor: ", tensor_1D_tf, type(tensor_1D_tf))

Numpy 1D array:  [1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>
PyTorch 1D tensor:  tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]) <class 'torch.Tensor'>
TensorFlow 1D tensor:  tf.Tensor([1 2 3 4 5 6 7 8 9], shape=(9,), dtype=int32) <class 'tensorflow.python.framework.ops.EagerTensor'>


In [6]:
list_2D = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

arr_2D = np.array(list_2D)
print("Numpy 2D array: ", arr_2D, type(arr_2D))

tensor_2D_pt = torch.tensor(list_2D)
print("PyTorch 2D tensor: ", tensor_2D_pt, type(tensor_2D_pt))

tensor_2D_tf = tf.convert_to_tensor(list_2D)
print("TensorFlow 2D tensor: ", tensor_2D_tf, type(tensor_2D_tf))


Numpy 2D array:  [[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'>
PyTorch 2D tensor:  tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]) <class 'torch.Tensor'>
TensorFlow 2D tensor:  tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32) <class 'tensorflow.python.framework.ops.EagerTensor'>
