## Daily AI Exercise - Numpy - pytorch - tensorflow - part 2

In [1]:
import numpy as np
import torch
import tensorflow as tf

### arange, range
- numpy: `np.arange(start, stop, step)`
- pytorch: `torch.arange(start, stop, step)`
- tensorflow: `tf.range(start, limit, delta)`

In [3]:
#1
numpy_arr = np.arange(0, 10, 1)
print(numpy_arr)
torch_tensor = torch.arange(0, 10, 1)
print(torch_tensor)
tf_tensor = tf.range(0, 10, 1)
print(tf_tensor)

[0 1 2 3 4 5 6 7 8 9]
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


### eye
- numpy: `np.eye(N)`
- pytorch: `torch.eye(n)`
- tensorflow: `tf.eye(num_rows, num_columns=None, batch_shape=None)`

In [4]:
numpy_arr = np.eye(3)
print(numpy_arr)
torch_tensor = torch.eye(3)
print(torch_tensor)
tf_tensor = tf.eye(3)
print(tf_tensor)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


### random
- numpy: `np.random.rand(d0, d1, ..., dn)`
- pytorch: `torch.rand(*sizes, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)`
- tensorflow: `tf.random.uniform(shape, minval=0, maxval=None, dtype=tf.dtypes.float32, seed=None, name=None)`
- numpy: `np.random.randn(d0, d1, ..., dn)`
- pytorch: `torch.randn(*sizes, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)`
- tensorflow: `tf.random.normal(shape, mean=0.0, stddev=1.0, dtype=tf.dtypes.float32, seed=None, name=None)`
- numpy: `np.random.randint(low, high=None, size=None, dtype=int)`
- pytorch: `torch.randint(low=0, high, size, dtype=None, layout=torch.strided, device=None, requires_grad=False)`
- tensorflow: `tf.random.uniform(shape, minval=0, maxval=None, dtype=tf.dtypes.float32, seed=None, name=None)`
- numpy: `np.random.seed(seed)`
- pytorch: `torch.manual_seed(seed)`
- tensorflow: `tf.random.set_seed(seed)`

In [7]:
np.random.seed(2024)
numpy_arr = np.random.rand(3, 4)
print(numpy_arr)

arr_randint = np.random.randint(-10, 10, size=(3, 4))
print(arr_randint)

[[0.58801452 0.69910875 0.18815196 0.04380856]
 [0.20501895 0.10606287 0.72724014 0.67940052]
 [0.4738457  0.44829582 0.01910695 0.75259834]]
[[ 5  1 -3  8]
 [-1 -4  0 -9]
 [-5  9 -6 -2]]


In [8]:
torch.manual_seed(2024)

torch_tensor = torch.rand(3, 4)
print(torch_tensor)

torch_tensor = torch.randint(-10, 10, (3, 4))
print(torch_tensor)


tensor([[0.5317, 0.8313, 0.9718, 0.1193],
        [0.1669, 0.3495, 0.2150, 0.6201],
        [0.4849, 0.7492, 0.1521, 0.5625]])
tensor([[  1,   8,   0,  -2],
        [ -9, -10,  -9,   0],
        [ -3,  -7,  -4,   8]])


In [9]:
tf.random.set_seed(2024)

tf_tensor = tf.random.uniform((3, 4))
print(tf_tensor)

tf_tensor = tf.random.uniform((3, 4), minval=-10, maxval=10, dtype=tf.int32)
print(tf_tensor)

tf.Tensor(
[[0.90034294 0.19453335 0.36069036 0.66361904]
 [0.76605344 0.2159369  0.6261736  0.07380784]
 [0.22062695 0.934368   0.93327904 0.69267046]], shape=(3, 4), dtype=float32)
tf.Tensor(
[[-3 -7  9  3]
 [ 2 -5 -3 -5]
 [ 4 -3 -3  5]], shape=(3, 4), dtype=int32)
