## Numpy Array và Pytorch/Tensorflow Tensor

In [1]:
import numpy as np
import torch
import tensorflow as tf

# Tạo một danh sách 1 chiều
list_1D = [1, 2, 3, 4, 5, 6, 7, 8, 9]

# Tạo một mảng 1 chiều từ danh sách
arr_1D = np.array(list_1D)
print("Mảng 1 chiều NumPy:\n", arr_1D, type(arr_1D))

# Tạo một tensor PyTorch từ danh sách
tensor_1D_pt = torch.tensor(list_1D)
print("Tensor PyTorch 1 chiều:\n", tensor_1D_pt)

# Tạo một tensor TensorFlow từ danh sách
tensor_1D_tf = tf.convert_to_tensor(list_1D)
print("Tensor TensorFlow 1 chiều:\n", tensor_1D_tf)


Mảng 1 chiều NumPy:
 [1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>
Tensor PyTorch 1 chiều:
 tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
Tensor TensorFlow 1 chiều:
 tf.Tensor([1 2 3 4 5 6 7 8 9], shape=(9,), dtype=int32)


In [2]:
# Tạo một danh sách 2 chiều
list_2D = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

# Tạo một mảng 2 chiều
arr_2D = np.array(list_2D)

# Kiểm tra hình dạng, kiểu dữ liệu và loại
print("Hình dạng của mảng:", arr_2D.shape)
print("Kiểu dữ liệu của mảng:", arr_2D.dtype)
print("Loại của mảng:", type(arr_2D))
print("Mảng:\n", arr_2D)

Hình dạng của mảng: (3, 3)
Kiểu dữ liệu của mảng: int32
Loại của mảng: <class 'numpy.ndarray'>
Mảng:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
# Tạo một tensor 2 chiều
tensor_2D_tf = tf.convert_to_tensor(list_2D)

# Kiểm tra hình dạng, kiểu dữ liệu, loại, thiết bị lưu trữ của tensor
print("Hình dạng của tensor:", tensor_2D_tf.shape)
print("Kiểu dữ liệu của tensor:", tensor_2D_tf.dtype)
print("Loại của tensor:", type(tensor_2D_tf))
print("Thiết bị lưu trữ của tensor:", tensor_2D_tf.device)
print("Tensor:\n", tensor_2D_tf)

Hình dạng của tensor: (3, 3)
Kiểu dữ liệu của tensor: <dtype: 'int32'>
Loại của tensor: <class 'tensorflow.python.framework.ops.EagerTensor'>
Thiết bị lưu trữ của tensor: /job:localhost/replica:0/task:0/device:CPU:0
Tensor:
 tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


In [4]:
# Tạo một tensor 2 chiều từ mảng NumPy
tensor_2D_pt = torch.tensor(arr_2D)

# Kiểm tra hình dạng, kiểu dữ liệu, loại, thiết bị lưu trữ của tensor
print("Hình dạng của tensor:", tensor_2D_pt.shape)
print("Kiểu dữ liệu của tensor:", tensor_2D_pt.dtype)
print("Loại của tensor:", type(tensor_2D_pt))
print("Thiết bị lưu trữ của tensor:", tensor_2D_pt.device)
print("Tensor:\n", tensor_2D_pt)


Hình dạng của tensor: torch.Size([3, 3])
Kiểu dữ liệu của tensor: torch.int32
Loại của tensor: <class 'torch.Tensor'>
Thiết bị lưu trữ của tensor: cpu
Tensor:
 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], dtype=torch.int32)


## Các Hàm Khởi Tạo Numpy Array và Pytorch/Tensorflow Tensor - Phần 1

In [5]:
# Numpy code
import numpy as np

# Tạo array toàn số 0
arr_zeros = np.zeros ((3 , 4))
print(arr_zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
# Tạo tensor toàn số 0
tensor_zeros = torch.zeros((3, 4))
print(tensor_zeros)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [8]:
# TensorFlow code
import tensorflow as tf

# Tạo tensor toàn số 0
tensor_zeros = tf.zeros((3, 4))
print(tensor_zeros)

tf.Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(3, 4), dtype=float32)


In [9]:
# Tạo array toàn số 1
arr_ones = np.ones((3, 4))
print(arr_ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [10]:
# Tạo tensor toàn số 1
tensor_ones = torch.ones((3, 4))
print(tensor_ones)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [11]:
# Tạo tensor toàn số 1
tensor_ones = tf.ones((3, 4))
print(tensor_ones)

tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(3, 4), dtype=float32)


In [12]:
# Tạo array toàn số 5
arr_fives = np.full((3, 4), 5)
print(arr_fives)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [13]:
# Tạo tensor toàn số 5
tensor_fives = torch.full((3, 4), 5)
print(tensor_fives)

tensor([[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]])


In [14]:
# Tạo tensor toàn số 5
tensor_fives = tf.fill((3, 4), 5)
print(tensor_fives)

tf.Tensor(
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]], shape=(3, 4), dtype=int32)


## Các Hàm Khởi Tạo Numpy Array và Pytorch/Tensorflow Tensor - Phần 2

In [15]:
# Tạo array trong khoảng [0 , 10), bước nhảy 1
arr_range = np.arange(0, 10, 1)
print(arr_range)

[0 1 2 3 4 5 6 7 8 9]


In [16]:
# Tạo tensor trong khoảng [0 , 10), bước nhảy 1
tensor_range = torch.arange(0, 10, 1)
print(tensor_range)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [17]:
# Tạo tensor trong khoảng [0 , 10), bước nhảy 1
tensor_range = tf.range(0, 10, 1)
print(tensor_range)

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


In [18]:
# Tạo array với đường chéo chính là 1, còn lại là 0
arr_eye = np.eye(3)
print(arr_eye)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
# Tạo tensor với đường chéo chính là 1, còn lại là 0
tensor_eye = torch.eye(3)
print(tensor_eye)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [20]:
# Tạo tensor với đường chéo chính là 1, còn lại là 0
tensor_eye = tf.eye(3)
print(tensor_eye)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [21]:
# Đặt seed để đảm bảo kết quả ngẫu nhiên có thể tái tạo được
np.random.seed(2024)

# Tạo một mảng với các giá trị ngẫu nhiên trong khoảng [0, 1) với kích thước (3, 4)
arr_rand = np.random.rand(3, 4)
print("Mảng ngẫu nhiên trong khoảng [0, 1):\n", arr_rand)

# Tạo một mảng với các giá trị ngẫu nhiên trong khoảng [-10, 10)
arr_randint = np.random.randint(-10, 10, size=(3, 4))
print("Mảng ngẫu nhiên trong khoảng [-10, 10):\n", arr_randint)

Mảng ngẫu nhiên trong khoảng [0, 1):
 [[0.58801452 0.69910875 0.18815196 0.04380856]
 [0.20501895 0.10606287 0.72724014 0.67940052]
 [0.4738457  0.44829582 0.01910695 0.75259834]]
Mảng ngẫu nhiên trong khoảng [-10, 10):
 [[ 5  1 -3  8]
 [-1 -4  0 -9]
 [-5  9 -6 -2]]


In [22]:
# Pytorch code
# Đặt seed để đảm bảo kết quả ngẫu nhiên có thể tái tạo được
torch.manual_seed(2024)

# Tạo tensor với các giá trị ngẫu nhiên trong khoảng [0, 1) với kích thước (3, 4)
tensor_rand = torch.rand(3, 4)
print("Tensor ngẫu nhiên trong khoảng [0, 1):\n", tensor_rand)

# Tạo tensor với các giá trị ngẫu nhiên trong khoảng [-10, 10)
tensor_randint = torch.randint(-10, 10, size=(3, 4))
print("Tensor ngẫu nhiên trong khoảng [-10, 10):\n", tensor_randint)

Tensor ngẫu nhiên trong khoảng [0, 1):
 tensor([[0.5317, 0.8313, 0.9718, 0.1193],
        [0.1669, 0.3495, 0.2150, 0.6201],
        [0.4849, 0.7492, 0.1521, 0.5625]])
Tensor ngẫu nhiên trong khoảng [-10, 10):
 tensor([[  1,   8,   0,  -2],
        [ -9, -10,  -9,   0],
        [ -3,  -7,  -4,   8]])


In [23]:
# TensorFlow code
# Đặt seed để đảm bảo kết quả ngẫu nhiên có thể tái tạo được
tf.random.set_seed(2024)

# Tạo tensor với các giá trị ngẫu nhiên trong khoảng [0, 1) với kích thước (3, 4)
tensor_rand = tf.random.uniform((3, 4))
print("Tensor ngẫu nhiên trong khoảng [0, 1):\n", tensor_rand)

# Tạo tensor với các giá trị ngẫu nhiên trong khoảng [-10, 10)
tensor_randint = tf.random.uniform((3, 4), -10, 10, dtype=tf.int32)
print("Tensor ngẫu nhiên trong khoảng [-10, 10):\n", tensor_randint)

Tensor ngẫu nhiên trong khoảng [0, 1):
 tf.Tensor(
[[0.90034294 0.19453335 0.36069036 0.66361904]
 [0.76605344 0.2159369  0.6261736  0.07380784]
 [0.22062695 0.934368   0.93327904 0.69267046]], shape=(3, 4), dtype=float32)
Tensor ngẫu nhiên trong khoảng [-10, 10):
 tf.Tensor(
[[-3 -7  9  3]
 [ 2 -5 -3 -5]
 [ 4 -3 -3  5]], shape=(3, 4), dtype=int32)


## Numpy, Pytorch và Tensorflow Hàm Stack và Concatenate

In [24]:
# numpy code
# Tạo 2 mảng
arr_1 = np.array([1, 2, 3])
arr_2 = np.array([4, 5, 6])

# Nối hai mảng tho trục ngang (axis = 0)
arr_3 = np.hstack((arr_1, arr_2))

# In kết quả
print("Mảng sau khi nối:\n", arr_3)

Mảng sau khi nối:
 [1 2 3 4 5 6]


In [25]:
# PyTorch code
# Tạo 2 tensor
tensor_1 = torch.tensor([1, 2, 3])
tensor_2 = torch.tensor([4, 5, 6])

# Nối hai tensor tho trục ngang (axis = 0)
tensor_3 = torch.hstack((tensor_1, tensor_2))

# In kết quả
print("Tensor sau khi nối:\n", tensor_3)

Tensor sau khi nối:
 tensor([1, 2, 3, 4, 5, 6])


In [27]:
# TensorFlow code
# Tạo 2 tensor
tensor_1 = tf.constant([1, 2, 3])
tensor_2 = tf.constant([4, 5, 6])

# Nối hai tensor tho trục ngang (axis = 0)
tensor_3 = tf.concat((tensor_1, tensor_2), axis=0)

# In kết quả
print("Tensor sau khi nối:\n", tensor_3)

Tensor sau khi nối:
 tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)


In [28]:
# Numpy code
# Tạo 2 mảng
arr_1 = np.array([1, 2, 3])
arr_2 = np.array([4, 5, 6])

# Nối hai mảng theo trục dọc (axis = 1)
arr_3 = np.vstack((arr_1, arr_2))

# In kết quả
print("Mảng sau khi nối:\n", arr_3)

Mảng sau khi nối:
 [[1 2 3]
 [4 5 6]]


In [29]:
# PyTorch code
# Tạo 2 tensor
tensor_1 = torch.tensor([1, 2, 3])
tensor_2 = torch.tensor([4, 5, 6])

# Nối hai tensor theo trục dọc (axis = 1)
tensor_3 = torch.vstack((tensor_1, tensor_2))

# In kết quả
print("Tensor sau khi nối:\n", tensor_3)

Tensor sau khi nối:
 tensor([[1, 2, 3],
        [4, 5, 6]])


### Concanate

In [30]:
# Numpy code
# Tạo mảng 2 chiều
arr_1 = np.array([[1, 2, 3], [4, 5, 6]])
arr_2 = np.array([[7, 8, 9], [10, 11, 12]])

# Nối hai mảng theo trục dọc (axis = 0)
arr_3 = np.concatenate((arr_1, arr_2), axis=0)

# Nối hai mảng theo trục ngang (axis = 1)
arr_4 = np.concatenate((arr_1, arr_2), axis=1)

# In kết quả
print("Mảng sau khi nối theo trục dọc:\n", arr_3)
print("Mảng sau khi nối theo trục ngang:\n", arr_4)


Mảng sau khi nối theo trục dọc:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Mảng sau khi nối theo trục ngang:
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [31]:
# PyTorch code
# Tạo tensor 2 chiều
tensor_1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
tensor_2 = torch.tensor([[7, 8, 9], [10, 11, 12]])

# Nối hai tensor theo trục dọc (axis = 0)
tensor_3 = torch.cat((tensor_1, tensor_2), dim=0)

# Nối hai tensor theo trục ngang (axis = 1)
tensor_4 = torch.cat((tensor_1, tensor_2), dim=1)

# In kết quả
print("Tensor sau khi nối theo trục dọc:\n", tensor_3)
print("Tensor sau khi nối theo trục ngang:\n", tensor_4)

Tensor sau khi nối theo trục dọc:
 tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])
Tensor sau khi nối theo trục ngang:
 tensor([[ 1,  2,  3,  7,  8,  9],
        [ 4,  5,  6, 10, 11, 12]])


In [32]:
# TensorFlow code
# Tạo tensor 2 chiều
tensor_1 = tf.constant([[1, 2, 3], [4, 5, 6]])
tensor_2 = tf.constant([[7, 8, 9], [10, 11, 12]])

# Nối hai tensor theo trục dọc (axis = 0)
tensor_3 = tf.concat((tensor_1, tensor_2), axis=0)

# Nối hai tensor theo trục ngang (axis = 1)
tensor_4 = tf.concat((tensor_1, tensor_2), axis=1)

# In kết quả
print("Tensor sau khi nối theo trục dọc:\n", tensor_3)
print("Tensor sau khi nối theo trục ngang:\n", tensor_4)

Tensor sau khi nối theo trục dọc:
 tf.Tensor(
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]], shape=(4, 3), dtype=int32)
Tensor sau khi nối theo trục ngang:
 tf.Tensor(
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]], shape=(2, 6), dtype=int32)


## Các Hàm Quan Trọng Trong Numpy, Pytorch, Tensorflow - Phần 2

In [33]:
# Create an aray 1D 1, 2, 3
arr_1D = np.array([1, 2, 3])
# 1D to 2D
arr_2D = arr_1D[np.newaxis, :]
# 2D to 5D
arr_5D = arr_2D[np.newaxis, :, np.newaxis, :, np.newaxis]
# print result
print("Mảng 1 chiều:\n", arr_1D)
print("Mảng 2 chiều:\n", arr_2D)
print("Mảng 5 chiều:\n", arr_5D)

Mảng 1 chiều:
 [1 2 3]
Mảng 2 chiều:
 [[1 2 3]]
Mảng 5 chiều:
 [[[[[1]
    [2]
    [3]]]]]


In [34]:
# expand_dims in PyTorch
# Create a tensor 1D 1, 2, 3
tensor_1D = torch.tensor([1, 2, 3])
# 1D to 2D
tensor_2D = tensor_1D[None, :]
# 2D to 5D
tensor_5D = tensor_2D[None, :, None, :, None]
# print result
print("Tensor 1 chiều:\n", tensor_1D)
print("Tensor 2 chiều:\n", tensor_2D)
print("Tensor 5 chiều:\n", tensor_5D)

Tensor 1 chiều:
 tensor([1, 2, 3])
Tensor 2 chiều:
 tensor([[1, 2, 3]])
Tensor 5 chiều:
 tensor([[[[[1],
           [2],
           [3]]]]])


In [35]:
# expand_dims in TensorFlow
# Create a tensor 1D 1, 2, 3
tensor_1D = tf.constant([1, 2, 3])
# 1D to 2D
tensor_2D = tf.expand_dims(tensor_1D, axis=0)
# 2D to 5D
tensor_5D = tensor_2D[tf.newaxis, :, tf.newaxis, :, tf.newaxis]
# print result
print("Tensor 1 chiều:\n", tensor_1D)
print("Tensor 2 chiều:\n", tensor_2D)  
print("Tensor 5 chiều:\n", tensor_5D)

Tensor 1 chiều:
 tf.Tensor([1 2 3], shape=(3,), dtype=int32)
Tensor 2 chiều:
 tf.Tensor([[1 2 3]], shape=(1, 3), dtype=int32)
Tensor 5 chiều:
 tf.Tensor(
[[[[[1]
    [2]
    [3]]]]], shape=(1, 1, 1, 3, 1), dtype=int32)


### reshape

In [36]:
# numpy code
# Create an array 2D
arr_2D = np.array([[1, 2, 3], [4, 5, 6]])
# 2D to 1D
arr_1D = np.reshape(arr_2D, newshape=(6,))

# print result
print("Mảng 2 chiều:\n", arr_2D)
print("Mảng 1 chiều:\n", arr_1D)


Mảng 2 chiều:
 [[1 2 3]
 [4 5 6]]
Mảng 1 chiều:
 [1 2 3 4 5 6]


In [37]:
## E1: create array [2, 3, 5, 7]. add new dimension at axis 0, then add dimension at axis 1, 3, 4
# numpy code
# Create an array 1D
arr_1D = np.array([2, 3, 5, 7])
# 1D to 2D
arr_2D = arr_1D[np.newaxis, :]
# 2D to 5D
arr_5D = arr_2D[:, np.newaxis, :, np.newaxis, np.newaxis]
# print result
print("Mảng 1 chiều:\n", arr_1D)
print("Mảng 2 chiều:\n", arr_2D)
print("Mảng 5 chiều:\n", arr_5D)

Mảng 1 chiều:
 [2 3 5 7]
Mảng 2 chiều:
 [[2 3 5 7]]
Mảng 5 chiều:
 [[[[[2]]

   [[3]]

   [[5]]

   [[7]]]]]


In [38]:
# PyTorch code
# Create a tensor 1D
tensor_1D = torch.tensor([2, 3, 5, 7])
# 1D to 2D
tensor_2D = tensor_1D[None, :]
# 2D to 5D
tensor_5D = tensor_2D[:, None, :, None, None]
# print result
print("Tensor 1 chiều:\n", tensor_1D)
print("Tensor 2 chiều:\n", tensor_2D)
print("Tensor 5 chiều:\n", tensor_5D)

Tensor 1 chiều:
 tensor([2, 3, 5, 7])
Tensor 2 chiều:
 tensor([[2, 3, 5, 7]])
Tensor 5 chiều:
 tensor([[[[[2]],

          [[3]],

          [[5]],

          [[7]]]]])


In [39]:
# TensorFlow code
# Create a tensor 1D
tensor_1D = tf.constant([2, 3, 5, 7])
# 1D to 2D
tensor_2D = tf.expand_dims(tensor_1D, axis=0)
# 2D to 5D
tensor_5D = tensor_2D[tf.newaxis, :, tf.newaxis, tf.newaxis, tf.newaxis]
# print result
print("Tensor 1 chiều:\n", tensor_1D)
print("Tensor 2 chiều:\n", tensor_2D)
print("Tensor 5 chiều:\n", tensor_5D)

Tensor 1 chiều:
 tf.Tensor([2 3 5 7], shape=(4,), dtype=int32)
Tensor 2 chiều:
 tf.Tensor([[2 3 5 7]], shape=(1, 4), dtype=int32)
Tensor 5 chiều:
 tf.Tensor([[[[[[2 3 5 7]]]]]], shape=(1, 1, 1, 1, 1, 4), dtype=int32)


In [40]:
## Ex2: create 3D array [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]]].
# Then reshape to shape (3, 6)
# numpy code
# Create an array 3D
arr_3D = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]]])
# Reshape to shape (3, 6)
arr_reshape = np.reshape(arr_3D, newshape=(3, 6))
# print result
print("Mảng 3 chiều:\n", arr_3D)
print("Mảng sau khi reshape:\n", arr_reshape)

Mảng 3 chiều:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
Mảng sau khi reshape:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]


In [41]:
# PyTorch code
# Create a tensor 3D
tensor_3D = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]]])
# Reshape to shape (3, 6)
tensor_reshape = torch.reshape(tensor_3D, (3, 6))
# print result
print("Tensor 3 chiều:\n", tensor_3D)
print("Tensor sau khi reshape:\n", tensor_reshape)

Tensor 3 chiều:
 tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]]])
Tensor sau khi reshape:
 tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18]])


In [42]:
# TensorFlow code
# Create a tensor 3D
tensor_3D = tf.constant([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]]])
# Reshape to shape (3, 6)
tensor_reshape = tf.reshape(tensor_3D, (3, 6))
# print result
print("Tensor 3 chiều:\n", tensor_3D)
print("Tensor sau khi reshape:\n", tensor_reshape)

Tensor 3 chiều:
 tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]], shape=(3, 2, 3), dtype=int32)
Tensor sau khi reshape:
 tf.Tensor(
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]], shape=(3, 6), dtype=int32)


## Các Hàm Quan Trọng Trong Numpy, Pytorch, Tensorflow - Phần 3

### function clip

In [43]:
np.random.seed(2024)

arr_rand = np.random.randint(-10, 10, (3, 3))
print("Mảng ngẫu nhiên:\n", arr_rand)

arr_clip = np.clip(arr_rand, a_min=3, a_max=8)
print("Mảng sau khi cắt:\n", arr_clip)


Mảng ngẫu nhiên:
 [[ -2 -10 -10]
 [ -6  -1  -9]
 [ -7   0  -8]]
Mảng sau khi cắt:
 [[3 3 3]
 [3 3 3]
 [3 3 3]]


In [44]:
# PyTorch code
torch.manual_seed(2024)

tensor_rand = torch.randint(-10, 10, (3, 3))
print("Tensor ngẫu nhiên:\n", tensor_rand)

tensor_clip = torch.clamp(tensor_rand, min=3, max=8)
print("Tensor sau khi cắt:\n", tensor_clip)

Tensor ngẫu nhiên:
 tensor([[  2,   0,  -6],
        [-10,  -7, -10],
        [  0,   1,   3]])
Tensor sau khi cắt:
 tensor([[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]])


In [45]:
# TensorFlow code
tf.random.set_seed(2024)

tensor_rand = tf.random.uniform((3, 3), -10, 10, dtype=tf.int32)
print("Tensor ngẫu nhiên:\n", tensor_rand)

tensor_clip = tf.clip_by_value(tensor_rand, clip_value_min=3, clip_value_max=8)
print("Tensor sau khi cắt:\n", tensor_clip)

Tensor ngẫu nhiên:
 tf.Tensor(
[[-6 -2  0]
 [-2  4  4]
 [-9  3  7]], shape=(3, 3), dtype=int32)
Tensor sau khi cắt:
 tf.Tensor(
[[3 3 3]
 [3 4 4]
 [3 3 7]], shape=(3, 3), dtype=int32)


In [46]:
## Ex1: create array in range [-5, 10) with size (4, 3). Then clip values in range [-2, 0]. seed = 2024
# numpy code
np.random.seed(2024)

arr_rand = np.random.randint(-5, 10, (4, 3))
print("Mảng ngẫu nhiên:\n", arr_rand)

arr_clip = np.clip(arr_rand, a_min=-2, a_max=0)
print("Mảng sau khi cắt:\n", arr_clip)

Mảng ngẫu nhiên:
 [[ 3  5 -5]
 [-5  6 -1]
 [ 9  2  4]
 [-4  7 -2]]
Mảng sau khi cắt:
 [[ 0  0 -2]
 [-2  0 -1]
 [ 0  0  0]
 [-2  0 -2]]


In [47]:
# PyTorch code
torch.manual_seed(2024)

tensor_rand = torch.randint(-5, 10, (4, 3))
print("Tensor ngẫu nhiên:\n", tensor_rand)

tensor_clip = torch.clamp(tensor_rand, min=-2, max=0)
print("Tensor sau khi cắt:\n", tensor_clip)

Tensor ngẫu nhiên:
 tensor([[-3,  0, -1],
        [ 0, -2,  0],
        [ 5,  6,  3],
        [ 4, -3, -1]])
Tensor sau khi cắt:
 tensor([[-2,  0, -1],
        [ 0, -2,  0],
        [ 0,  0,  0],
        [ 0, -2, -1]])


In [48]:
# TensorFlow code
tf.random.set_seed(2024)

tensor_rand = tf.random.uniform((4, 3), -5, 10, dtype=tf.int32)
print("Tensor ngẫu nhiên:\n", tensor_rand)

tensor_clip = tf.clip_by_value(tensor_rand, clip_value_min=-2, clip_value_max=0)
print("Tensor sau khi cắt:\n", tensor_clip)

Tensor ngẫu nhiên:
 tf.Tensor(
[[ 4  3  0]
 [ 3  9  9]
 [-4 -2  2]
 [ 6  2  0]], shape=(4, 3), dtype=int32)
Tensor sau khi cắt:
 tf.Tensor(
[[ 0  0  0]
 [ 0  0  0]
 [-2 -2  0]
 [ 0  0  0]], shape=(4, 3), dtype=int32)


## Indexing Trong Numpy, Pytorch và Tensorflow - Phần 1

In [49]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
# slicing 
sliced_array_1 = array_2d[0:1, 1:2]
print(f"Sliced array 1:\n{sliced_array_1}")
# decrease dimension
sliced_array_2 = array_2d[0, 1:2]
print(f"Sliced array 2:\n{sliced_array_2}")
# decrease dimension
sliced_array_3 = array_2d[0, 1]
print(f"Sliced array 3:\n{sliced_array_3}")
# take all values
sliced_array_4 = array_2d[:, :]
print(f"Sliced array 4:\n{sliced_array_4}")

Sliced array 1:
[[2]]
Sliced array 2:
[2]
Sliced array 3:
2
Sliced array 4:
[[1 2 3]
 [4 5 6]]


In [50]:
# PyTorch code
tensor_2d = torch.tensor([[1, 2, 3], [4, 5, 6]])
# slicing
sliced_tensor_1 = tensor_2d[0:1, 1:2]
print(f"Sliced tensor 1:\n{sliced_tensor_1}")
# decrease dimension
sliced_tensor_2 = tensor_2d[0, 1:2]
print(f"Sliced tensor 2:\n{sliced_tensor_2}")
# decrease dimension
sliced_tensor_3 = tensor_2d[0, 1]
print(f"Sliced tensor 3:\n{sliced_tensor_3}")
# take all values
sliced_tensor_4 = tensor_2d[:, :]
print(f"Sliced tensor 4:\n{sliced_tensor_4}")

Sliced tensor 1:
tensor([[2]])
Sliced tensor 2:
tensor([2])
Sliced tensor 3:
2
Sliced tensor 4:
tensor([[1, 2, 3],
        [4, 5, 6]])


In [51]:
# TensorFlow code
tensor_2d = tf.constant([[1, 2, 3], [4, 5, 6]])
# slicing
sliced_tensor_1 = tensor_2d[0:1, 1:2]
print(f"Sliced tensor 1:\n{sliced_tensor_1}")
# decrease dimension
sliced_tensor_2 = tensor_2d[0, 1:2]
print(f"Sliced tensor 2:\n{sliced_tensor_2}")
# decrease dimension
sliced_tensor_3 = tensor_2d[0, 1]
print(f"Sliced tensor 3:\n{sliced_tensor_3}")
# take all values
sliced_tensor_4 = tensor_2d[:, :]
print(f"Sliced tensor 4:\n{sliced_tensor_4}")

Sliced tensor 1:
[[2]]
Sliced tensor 2:
[2]
Sliced tensor 3:
2
Sliced tensor 4:
[[1 2 3]
 [4 5 6]]


In [57]:
## Ex1: create array of size (3, 2, 3) with values from 1 to 18.
## using slicing to take index (0,1) of array 2D and keep the dimension
# numpy code
# Create an array 3D
arr_3D = np.arange(1, 19).reshape(3, 2, 3)
# Slicing
sliced_arr = arr_3D[:, 0, 1]
# print result
print("Mảng 3 chiều:\n", arr_3D)
print("Mảng sau khi cắt:\n", sliced_arr)

Mảng 3 chiều:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
Mảng sau khi cắt:
 [ 2  8 14]


In [59]:
# PyTorch code
# Create a tensor 3D
tensor_3D = torch.arange(1, 19).reshape(3, 2, 3)
# Slicing
sliced_tensor = tensor_3D[:, 0, 1]
# print result
print("Tensor 3 chiều:\n", tensor_3D)
print("Tensor sau khi cắt:\n", sliced_tensor)

Tensor 3 chiều:
 tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]]])
Tensor sau khi cắt:
 tensor([ 2,  8, 14])


In [60]:
# TensorFlow code
# Create a tensor 3D
tensor_3D = tf.range(1, 19, dtype=tf.int32)
tensor_3D = tf.reshape(tensor_3D, (3, 2, 3))
# Slicing
sliced_tensor = tensor_3D[:, 0, 1]
# print result
print("Tensor 3 chiều:\n", tensor_3D)
print("Tensor sau khi cắt:\n", sliced_tensor)

Tensor 3 chiều:
 tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]], shape=(3, 2, 3), dtype=int32)
Tensor sau khi cắt:
 tf.Tensor([ 2  8 14], shape=(3,), dtype=int32)


## Indexing Trong Numpy, Pytorch và Tensorflow - Phần 2

In [61]:
arr_2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
# get the second row by decreasing dimension
row_1_arr_1 = arr_2d[1, :]
print(f"Row 1 array 1:\n{row_1_arr_1}")

# get the second row by keeping dimension
row_1_arr_2 = arr_2d[1:2, :]
print(f"Row 1 array 2:\n{row_1_arr_2}")

# get the third col by decreasing dimension
col_2_arr_1 = arr_2d[:, 2]
print(f"Col 2 array 1:\n{col_2_arr_1}")

# get the third col by keeping dimension
col_2_arr_2 = arr_2d[:, 2:3]
print(f"Col 2 array 2:\n{col_2_arr_2}")

Row 1 array 1:
[4 5 6]
Row 1 array 2:
[[4 5 6]]
Col 2 array 1:
[3 6 9]
Col 2 array 2:
[[3]
 [6]
 [9]]


In [63]:
# PyTorch code
tensor_2d = torch.tensor([[1,2,3], [4,5,6], [7,8,9]])
# get the second row by decreasing dimension
row_1_tensor_1 = tensor_2d[1, :]
print(f"Row 1 tensor 1:\n{row_1_tensor_1}")
# get the second row by keeping dimension
row_1_tensor_2 = tensor_2d[1:2, :]
print(f"Row 1 tensor 2:\n{row_1_tensor_2}")
# get the third col by decreasing dimension
col_2_tensor_1 = tensor_2d[:, 2]
print(f"Col 2 tensor 1:\n{col_2_tensor_1}")
# get the third col by keeping dimension
col_2_tensor_2 = tensor_2d[:, 2:3]
print(f"Col 2 tensor 2:\n{col_2_tensor_2}")

Row 1 tensor 1:
tensor([4, 5, 6])
Row 1 tensor 2:
tensor([[4, 5, 6]])
Col 2 tensor 1:
tensor([3, 6, 9])
Col 2 tensor 2:
tensor([[3],
        [6],
        [9]])


In [64]:
# Tensorflow code
tensor_2d = tf.constant([[1,2,3], [4,5,6], [7,8,9]])
# get the second row by decreasing dimension
row_1_tensor_1 = tensor_2d[1, :]
print(f"Row 1 tensor 1:\n{row_1_tensor_1}")
# get the second row by keeping dimension
row_1_tensor_2 = tensor_2d[1:2, :]
print(f"Row 1 tensor 2:\n{row_1_tensor_2}")
# get the third col by decreasing dimension
col_2_tensor_1 = tensor_2d[:, 2]
print(f"Col 2 tensor 1:\n{col_2_tensor_1}")
# get the third col by keeping dimension
col_2_tensor_2 = tensor_2d[:, 2:3]
print(f"Col 2 tensor 2:\n{col_2_tensor_2}")

Row 1 tensor 1:
[4 5 6]
Row 1 tensor 2:
[[4 5 6]]
Col 2 tensor 1:
[3 6 9]
Col 2 tensor 2:
[[3]
 [6]
 [9]]


### Boolean indices

In [4]:
array_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
# mask
boolean_mask = array_2d>5
filtered_result = array_2d[boolean_mask]
# print result
print(f"Original array: {array_2d}")
print(f"Boolean mask: {boolean_mask}")
print(f"Filtered result: {filtered_result}")

Original array: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Boolean mask: [[False False False]
 [False False  True]
 [ True  True  True]]
Filtered result: [6 7 8 9]


In [5]:
# PyTorch code
tensor_2d = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
# mask
boolean_mask = tensor_2d>5
filtered_result = tensor_2d[boolean_mask]
# print result
print(f"Original tensor: {tensor_2d}")
print(f"Boolean mask: {boolean_mask}")
print(f"Filtered result: {filtered_result}")


Original tensor: tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Boolean mask: tensor([[False, False, False],
        [False, False,  True],
        [ True,  True,  True]])
Filtered result: tensor([6, 7, 8, 9])


In [6]:
# TensorFlow code
tensor_2d = tf.constant([[1,2,3],[4,5,6],[7,8,9]])
# mask
boolean_mask = tensor_2d>5
filtered_result = tf.boolean_mask(tensor_2d, boolean_mask)
# print result
print(f"Original tensor: {tensor_2d}")
print(f"Boolean mask: {boolean_mask}")
print(f"Filtered result: {filtered_result}")

Original tensor: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Boolean mask: [[False False False]
 [False False  True]
 [ True  True  True]]
Filtered result: [6 7 8 9]


In [7]:
## Ex1: given 2D list [[1,0,1],[0,1,0],[1,0,1]]. Take second row (index=1) by 2 ways
## Take first col (index=0) by 2 ways
# numpy code
# Create an array 2D
arr_2D = np.array([[1,0,1],[0,1,0],[1,0,1]])
# Take second row by decreasing dimension
row_1_arr_1 = arr_2D[1, :]
# Take second row by keeping dimension
row_1_arr_2 = arr_2D[1:2, :]
# Take first col by decreasing dimension
col_0_arr_1 = arr_2D[:, 0]
# Take first col by keeping dimension
col_0_arr_2 = arr_2D[:, 0:1]
# print result
print("Mảng 2 chiều:\n", arr_2D)
print("Hàng thứ 2 cách 1:\n", row_1_arr_1)
print("Hàng thứ 2 cách 2:\n", row_1_arr_2)
print("Cột thứ 1 cách 1:\n", col_0_arr_1)
print("Cột thứ 1 cách 2:\n", col_0_arr_2)

Mảng 2 chiều:
 [[1 0 1]
 [0 1 0]
 [1 0 1]]
Hàng thứ 2 cách 1:
 [0 1 0]
Hàng thứ 2 cách 2:
 [[0 1 0]]
Cột thứ 1 cách 1:
 [1 0 1]
Cột thứ 1 cách 2:
 [[1]
 [0]
 [1]]


In [8]:
# PyTorch code
# Create a tensor 2D
tensor_2D = torch.tensor([[1,0,1],[0,1,0],[1,0,1]])
# Take second row by decreasing dimension
row_1_tensor_1 = tensor_2D[1, :]
# Take second row by keeping dimension
row_1_tensor_2 = tensor_2D[1:2, :]
# Take first col by decreasing dimension
col_0_tensor_1 = tensor_2D[:, 0]
# Take first col by keeping dimension
col_0_tensor_2 = tensor_2D[:, 0:1]
# print result
print("Tensor 2 chiều:\n", tensor_2D)
print("Hàng thứ 2 cách 1:\n", row_1_tensor_1)
print("Hàng thứ 2 cách 2:\n", row_1_tensor_2)
print("Cột thứ 1 cách 1:\n", col_0_tensor_1)

Tensor 2 chiều:
 tensor([[1, 0, 1],
        [0, 1, 0],
        [1, 0, 1]])
Hàng thứ 2 cách 1:
 tensor([0, 1, 0])
Hàng thứ 2 cách 2:
 tensor([[0, 1, 0]])
Cột thứ 1 cách 1:
 tensor([1, 0, 1])


In [10]:
# TensorFlow code
# Create a tensor 2D
tensor_2D = tf.constant([[1,0,1],[0,1,0],[1,0,1]])
# Take second row by decreasing dimension
row_1_tensor_1 = tensor_2D[1, :]
# Take second row by keeping dimension
row_1_tensor_2 = tensor_2D[1:2, :]
# Take first col by decreasing dimension
col_0_tensor_1 = tensor_2D[:, 0]
# Take first col by keeping dimension
col_0_tensor_2 = tensor_2D[:, 0:1]
# print result
print("Tensor 2 chiều:\n", tensor_2D)
print("Hàng thứ 2 cách 1:\n", row_1_tensor_1)
print("Hàng thứ 2 cách 2:\n", row_1_tensor_2)
print("Cột thứ 1 cách 1:\n", col_0_tensor_1)
print("Cột thứ 1 cách 2:\n", col_0_tensor_2)

Tensor 2 chiều:
 tf.Tensor(
[[1 0 1]
 [0 1 0]
 [1 0 1]], shape=(3, 3), dtype=int32)
Hàng thứ 2 cách 1:
 tf.Tensor([0 1 0], shape=(3,), dtype=int32)
Hàng thứ 2 cách 2:
 tf.Tensor([[0 1 0]], shape=(1, 3), dtype=int32)
Cột thứ 1 cách 1:
 tf.Tensor([1 0 1], shape=(3,), dtype=int32)
Cột thứ 1 cách 2:
 tf.Tensor(
[[1]
 [0]
 [1]], shape=(3, 1), dtype=int32)


In [11]:
## Ex2: given 2D array with random values in range [-10, 10) with size (3, 3).
## use boolean mask to take value > 0. Seed = 2024
# numpy code
# Set seed
np.random.seed(2024)
# Create an array 2D
arr_2D = np.random.randint(-10, 10, (3, 3))
# Boolean mask
boolean_mask = arr_2D > 0
# Filtered result
filtered_result = arr_2D[boolean_mask]
# print result
print("Mảng 2 chiều:\n", arr_2D)
print("Boolean mask:\n", boolean_mask)
print("Filtered result:\n", filtered_result)

Mảng 2 chiều:
 [[ -2 -10 -10]
 [ -6  -1  -9]
 [ -7   0  -8]]
Boolean mask:
 [[False False False]
 [False False False]
 [False False False]]
Filtered result:
 []


In [12]:
# PyTorch code
# Set seed
torch.manual_seed(2024)
# Create a tensor 2D
tensor_2D = torch.randint(-10, 10, (3, 3))
# Boolean mask
boolean_mask = tensor_2D > 0
# Filtered result
filtered_result = tensor_2D[boolean_mask]
# print result
print("Tensor 2 chiều:\n", tensor_2D)
print("Boolean mask:\n", boolean_mask)
print("Filtered result:\n", filtered_result)

Tensor 2 chiều:
 tensor([[  2,   0,  -6],
        [-10,  -7, -10],
        [  0,   1,   3]])
Boolean mask:
 tensor([[ True, False, False],
        [False, False, False],
        [False,  True,  True]])
Filtered result:
 tensor([2, 1, 3])


In [13]:
# TensorFlow code
# Set seed
tf.random.set_seed(2024)
# Create a tensor 2D
tensor_2D = tf.random.uniform((3, 3), -10, 10, dtype=tf.int32)
# Boolean mask
boolean_mask = tensor_2D > 0
# Filtered result
filtered_result = tf.boolean_mask(tensor_2D, boolean_mask)
# print result
print("Tensor 2 chiều:\n", tensor_2D)
print("Boolean mask:\n", boolean_mask)
print("Filtered result:\n", filtered_result)

Tensor 2 chiều:
 tf.Tensor(
[[-6 -2  0]
 [-2  4  4]
 [-9  3  7]], shape=(3, 3), dtype=int32)
Boolean mask:
 tf.Tensor(
[[False False False]
 [False  True  True]
 [False  True  True]], shape=(3, 3), dtype=bool)
Filtered result:
 tf.Tensor([4 4 3 7], shape=(4,), dtype=int32)


## Các Phép Tính Numpy, Pytorch và Tensorflow - Phần 1

### Addition

In [20]:
arr_1 = np.array([[1,-2,1],[-3,1,0],[-2,5,1]])
arr_2 = np.array([[1,3,5],[2,4,6],[3,5,7]])
# '+'
arr_add_1 = arr_1 + arr_2
# np.add()
arr_add_2 = np.add(arr_1, arr_2)
# print result
print(f"Addition 1: {arr_add_1}")
print(f"Addition 2: {arr_add_2}")

Addition 1: [[ 2  1  6]
 [-1  5  6]
 [ 1 10  8]]
Addition 2: [[ 2  1  6]
 [-1  5  6]
 [ 1 10  8]]


In [21]:
# PyTorch code
tensor_1 = torch.tensor([[1,-2,1],[-3,1,0],[-2,5,1]])
tensor_2 = torch.tensor([[1,3,5],[2,4,6],[3,5,7]])
# '+'
tensor_add_1 = tensor_1 + tensor_2
# torch.add()
tensor_add_2 = torch.add(tensor_1, tensor_2)
# print result
print(f"Addition 1: {tensor_add_1}")
print(f"Addition 2: {tensor_add_2}")

Addition 1: tensor([[ 2,  1,  6],
        [-1,  5,  6],
        [ 1, 10,  8]])
Addition 2: tensor([[ 2,  1,  6],
        [-1,  5,  6],
        [ 1, 10,  8]])


In [23]:
# TensorFlow code
tensor_1 = tf.constant([[1,-2,1],[-3,1,0],[-2,5,1]])
tensor_2 = tf.constant([[1,3,5],[2,4,6],[3,5,7]])
# '+'
tensor_add_1 = tensor_1 + tensor_2
# tf.add()
tensor_add_2 = tf.add(tensor_1, tensor_2)
# print result
print(f"Addition 1: {tensor_add_1}")
print(f"Addition 2: {tensor_add_2}")

Addition 1: [[ 2  1  6]
 [-1  5  6]
 [ 1 10  8]]
Addition 2: [[ 2  1  6]
 [-1  5  6]
 [ 1 10  8]]


### Subtraction

In [24]:
arr_1 = np.array([[1,-2,1],[-3,1,0],[-2,5,1]])
arr_2 = np.array([[1,3,5],[2,4,6],[3,5,7]])
# '-'
arr_sub_1 = arr_1 - arr_2
# np.subtract()
arr_sub_2 = np.subtract(arr_1, arr_2)
# print result
print(f"Subtraction 1: {arr_sub_1}")
print(f"Subtraction 2: {arr_sub_2}")

Subtraction 1: [[ 0 -5 -4]
 [-5 -3 -6]
 [-5  0 -6]]
Subtraction 2: [[ 0 -5 -4]
 [-5 -3 -6]
 [-5  0 -6]]


In [25]:
# PyTorch code
tensor_1 = torch.tensor([[1,-2,1],[-3,1,0],[-2,5,1]])
tensor_2 = torch.tensor([[1,3,5],[2,4,6],[3,5,7]])
# '-'
tensor_sub_1 = tensor_1 - tensor_2
# torch.sub()
tensor_sub_2 = torch.sub(tensor_1, tensor_2)
# print result
print(f"Subtraction 1: {tensor_sub_1}")
print(f"Subtraction 2: {tensor_sub_2}")

Subtraction 1: tensor([[ 0, -5, -4],
        [-5, -3, -6],
        [-5,  0, -6]])
Subtraction 2: tensor([[ 0, -5, -4],
        [-5, -3, -6],
        [-5,  0, -6]])


In [26]:
# TensorFlow code
tensor_1 = tf.constant([[1,-2,1],[-3,1,0],[-2,5,1]])
tensor_2 = tf.constant([[1,3,5],[2,4,6],[3,5,7]])
# '-'
tensor_sub_1 = tensor_1 - tensor_2
# tf.subtract()
tensor_sub_2 = tf.subtract(tensor_1, tensor_2)
# print result
print(f"Subtraction 1: {tensor_sub_1}")
print(f"Subtraction 2: {tensor_sub_2}")

Subtraction 1: [[ 0 -5 -4]
 [-5 -3 -6]
 [-5  0 -6]]
Subtraction 2: [[ 0 -5 -4]
 [-5 -3 -6]
 [-5  0 -6]]


## Các Phép Tính Numpy, Pytorch và Tensorflow - Phần 2

### Multiplication

In [27]:
arr_1 = np.array([[1,-2,1],[-3,1,0],[-2,5,1]])
arr_2 = np.array([[1,3,5],[2,4,6],[3,5,7]])
# '*'
arr_mul_1 = arr_1 * arr_2
# np.multiply()
arr_mul_2 = np.multiply(arr_1, arr_2)
# print result
print(f"Multiplication 1: {arr_mul_1}")
print(f"Multiplication 2: {arr_mul_2}")

Multiplication 1: [[ 1 -6  5]
 [-6  4  0]
 [-6 25  7]]
Multiplication 2: [[ 1 -6  5]
 [-6  4  0]
 [-6 25  7]]


In [28]:
# PyTorch code
tensor_1 = torch.tensor([[1,-2,1],[-3,1,0],[-2,5,1]])
tensor_2 = torch.tensor([[1,3,5],[2,4,6],[3,5,7]])
# '*'
tensor_mul_1 = tensor_1 * tensor_2
# torch.mul()
tensor_mul_2 = torch.mul(tensor_1, tensor_2)
# print result
print(f"Multiplication 1: {tensor_mul_1}")
print(f"Multiplication 2: {tensor_mul_2}")

Multiplication 1: tensor([[ 1, -6,  5],
        [-6,  4,  0],
        [-6, 25,  7]])
Multiplication 2: tensor([[ 1, -6,  5],
        [-6,  4,  0],
        [-6, 25,  7]])


In [29]:
# TensorFlow code
tensor_1 = tf.constant([[1,-2,1],[-3,1,0],[-2,5,1]])
tensor_2 = tf.constant([[1,3,5],[2,4,6],[3,5,7]])
# '*'
tensor_mul_1 = tensor_1 * tensor_2
# tf.multiply()
tensor_mul_2 = tf.multiply(tensor_1, tensor_2)
# print result
print(f"Multiplication 1: {tensor_mul_1}")
print(f"Multiplication 2: {tensor_mul_2}")

Multiplication 1: [[ 1 -6  5]
 [-6  4  0]
 [-6 25  7]]
Multiplication 2: [[ 1 -6  5]
 [-6  4  0]
 [-6 25  7]]


### Division

In [30]:
arr_1 = np.array([[1,-2,1],[-3,1,0],[-2,5,1]])
arr_2 = np.array([[1,3,5],[2,4,6],[3,5,7]])
# '/'
arr_div_1 = arr_1 / arr_2
# np.divide()
arr_div_2 = np.divide(arr_1, arr_2)
# print result
print(f"Division 1: {arr_div_1}")
print(f"Division 2: {arr_div_2}")

Division 1: [[ 1.         -0.66666667  0.2       ]
 [-1.5         0.25        0.        ]
 [-0.66666667  1.          0.14285714]]
Division 2: [[ 1.         -0.66666667  0.2       ]
 [-1.5         0.25        0.        ]
 [-0.66666667  1.          0.14285714]]


In [31]:
# PyTorch code
tensor_1 = torch.tensor([[1,-2,1],[-3,1,0],[-2,5,1]])
tensor_2 = torch.tensor([[1,3,5],[2,4,6],[3,5,7]])
# '/'
tensor_div_1 = tensor_1 / tensor_2
# torch.div()
tensor_div_2 = torch.div(tensor_1, tensor_2)
# print result
print(f"Division 1: {tensor_div_1}")
print(f"Division 2: {tensor_div_2}")

Division 1: tensor([[ 1.0000, -0.6667,  0.2000],
        [-1.5000,  0.2500,  0.0000],
        [-0.6667,  1.0000,  0.1429]])
Division 2: tensor([[ 1.0000, -0.6667,  0.2000],
        [-1.5000,  0.2500,  0.0000],
        [-0.6667,  1.0000,  0.1429]])


In [32]:
# TensorFlow code
tensor_1 = tf.constant([[1,-2,1],[-3,1,0],[-2,5,1]])
tensor_2 = tf.constant([[1,3,5],[2,4,6],[3,5,7]])
# '/'
tensor_div_1 = tensor_1 / tensor_2
# tf.divide()
tensor_div_2 = tf.divide(tensor_1, tensor_2)
# print result
print(f"Division 1: {tensor_div_1}")
print(f"Division 2: {tensor_div_2}")

Division 1: [[ 1.         -0.66666667  0.2       ]
 [-1.5         0.25        0.        ]
 [-0.66666667  1.          0.14285714]]
Division 2: [[ 1.         -0.66666667  0.2       ]
 [-1.5         0.25        0.        ]
 [-0.66666667  1.          0.14285714]]


## Các Phép Tính Numpy, Pytorch và Tensorflow - Phần 3

### Inner product & matrix multiplication

In [35]:
arr_1 = np.array([1,4,7])
arr_2 = np.array([9,2,3])
arr_3 = np.random.randint(-10, 10, (3, 3))
arr_4 = np.random.randint(-10, 10, (3, 3))
np.random.seed(2024)
# inner product
result_dot = np.dot(arr_1, arr_2)
# matrix multiplication
result_matmul = np.matmul(arr_3, arr_4)
# print result
print(f"Inner product: {result_dot}")
print(f"Matrix multiplication: {result_matmul}")

Inner product: 38
Matrix multiplication: [[ -1 -30 -77]
 [ 11  33  46]
 [ 33 -21 -42]]


In [36]:
# PyTorch code
tensor_1 = torch.tensor([1,4,7])
tensor_2 = torch.tensor([9,2,3])
tensor_3 = torch.randint(-10, 10, (3, 3))
tensor_4 = torch.randint(-10, 10, (3, 3))
torch.manual_seed(2024)
# inner product
result_dot = torch.dot(tensor_1, tensor_2)
# matrix multiplication
result_matmul = torch.matmul(tensor_3, tensor_4)
# print result
print(f"Inner product: {result_dot}")
print(f"Matrix multiplication: {result_matmul}")

Inner product: 38
Matrix multiplication: tensor([[-184,  -34,   23],
        [ -65,  -32,   61],
        [  -9,   26,  -76]])


In [37]:
# TensorFlow code
tensor_1 = tf.constant([1,4,7])
tensor_2 = tf.constant([9,2,3])
tensor_3 = tf.random.uniform((3, 3), -10, 10, dtype=tf.int32)
tensor_4 = tf.random.uniform((3, 3), -10, 10, dtype=tf.int32)
tf.random.set_seed(2024)
# inner product
result_dot = tf.tensordot(tensor_1, tensor_2, axes=1)
# matrix multiplication
result_matmul = tf.matmul(tensor_3, tensor_4)
# print result
print(f"Inner product: {result_dot}")
print(f"Matrix multiplication: {result_matmul}")

Inner product: 38
Matrix multiplication: [[ 38  45  24]
 [-26   0 -27]
 [  6  27  15]]


## Các Phép Tính Numpy, Pytorch và Tensorflow - Transpose và Summation

In [38]:
np.random.seed(2024)
arr_1 = np.random.randint(-10, 10, (3, 4))
# transpose
arr_T = arr_1.T
# sum of all elements
arr_sum_all = np.sum(arr_1)
# sum via column
column_sum = np.sum(arr_1, axis=0)
# sum via row
row_sum = np.sum(arr_1, axis=1)
# print result
print(f"Original array: {arr_1}")
print(f"Sum of all elements: {arr_sum_all}")
print(f"Sum via column: {column_sum}")
print(f"Sum via row: {row_sum}")

Original array: [[ -2 -10 -10  -6]
 [ -1  -9  -7   0]
 [ -8 -10  -5   7]]
Sum of all elements: -61
Sum via column: [-11 -29 -22   1]
Sum via row: [-28 -17 -16]


In [2]:
# PyTorch code
torch.manual_seed(2024)
tensor_1 = torch.randint(-10, 10, (3, 4))
# transpose
tensor_T = tensor_1.T
# sum of all elements
tensor_sum_all = torch.sum(tensor_1)
# sum via column
column_sum = torch.sum(tensor_1, axis=0)
# sum via row
row_sum = torch.sum(tensor_1, axis=1)
# print result
print(f"Original tensor: {tensor_1}")
print(f"Sum of all elements: {tensor_sum_all}")
print(f"Sum via column: {column_sum}")
print(f"Sum via row: {row_sum}")

Original tensor: tensor([[  2,   0,  -6, -10],
        [ -7, -10,   0,   1],
        [  3,   9,   7,  -6]])
Sum of all elements: -17
Sum via column: tensor([ -2,  -1,   1, -15])
Sum via row: tensor([-14, -16,  13])


In [3]:
# TensorFlow code
tf.random.set_seed(2024)
tensor_1 = tf.random.uniform((3, 4), -10, 10, dtype=tf.int32)
# transpose
tensor_T = tf.transpose(tensor_1)
# sum of all elements
tensor_sum_all = tf.reduce_sum(tensor_1)
# sum via column
column_sum = tf.reduce_sum(tensor_1, axis=0)
# sum via row
row_sum = tf.reduce_sum(tensor_1, axis=1)
# print result
print(f"Original tensor: {tensor_1}")
print(f"Sum of all elements: {tensor_sum_all}")
print(f"Sum via column: {column_sum}")
print(f"Sum via row: {row_sum}")

Original tensor: [[-6 -2  0 -2]
 [ 4  4 -9  3]
 [ 7  1  2 -5]]
Sum of all elements: -3
Sum via column: [ 5  3 -7 -4]
Sum via row: [-10   2   5]
